apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
spec:
  type: LoadBalancer       # Ask GKE to create Public Load Balancer
  selector:
    app: hello-app          # Find pods with this label
  ports:
    - port: 80            # Public port exposed to internet
      targetPort: 8080     # Pod port where Spring Boot runs